apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-fanis-oct1 
  janus-idp.io/tekton: test-fanis-oct1
  backstage.io/kubernetes-id: test-fanis-oct1
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: test-fanis-oct1
resources: 
- application-dev.yaml